// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgsoGNtmlIFsYM3wz9DmgkAVAbIVlivCs',
    appId: '1:285599457074:web:07eaef1a03ad534dab812b',
    messagingSenderId: '285599457074',
    projectId: 'nvpolitica',
    authDomain: 'nvpolitica.firebaseapp.com',
    databaseURL: 'https://nvpolitica-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nvpolitica.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6HcDnpbyRYygyt82RONL5tmt1L1SERzk',
    appId: '1:285599457074:android:4e54093c817a367eab812b',
    messagingSenderId: '285599457074',
    projectId: 'nvpolitica',
    databaseURL: 'https://nvpolitica-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nvpolitica.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0uesFHxesT3meEzqCYLTtqYaOhW2Bx0w',
    appId: '1:285599457074:ios:87bdf8be56452e4fab812b',
    messagingSenderId: '285599457074',
    projectId: 'nvpolitica',
    databaseURL: 'https://nvpolitica-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nvpolitica.appspot.com',
    iosBundleId: 'com.example.novaPolitica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0uesFHxesT3meEzqCYLTtqYaOhW2Bx0w',
    appId: '1:285599457074:ios:87bdf8be56452e4fab812b',
    messagingSenderId: '285599457074',
    projectId: 'nvpolitica',
    databaseURL: 'https://nvpolitica-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'nvpolitica.appspot.com',
    iosBundleId: 'com.example.novaPolitica',
  );
}
